### ISSUE TITLE
Create sample content for Questionnaire $prepopulate

### ISSUE THREAD

**Issue by JPercival** [cqframework/clinical-reasoning#214]
As an implementor of the $prepopulate operation, I need sample content so that I can validate that my implementation is correct.

Design:
Create a PlanDefintiion that uses the $prepopulate operation

Need PlanDefinition, ActivityDefinition. We already have the example Questionnaire/Library and sample data sets.

Contact Rob for getting the existing content.

Acceptance Criteria:
PlanDefinition (and supporting content) using $prepopulate is attached to this story

**Comment by Capt-Mac** [comment]
@rob-reynolds  to review sample content created by Brenin
