### ISSUE TITLE
Implement StructureDefinition based $extract

### ISSUE THREAD

**Issue by JPercival** [cqframework/clinical-reasoning#216]
I have not been able to find a way to correctly handle definition based extraction without having the StructureDefinition of the resource type available to determine if a given property is an array or not. Perhaps something can be added to the item, either in the definition or on the item itself. However, having the StructureDefinition is absolutely required for generating a Questionnaire item for a CaseFeature so it is likely that we will have it.

**Comment by barhodes** [comment]
This has been implemented.
