### ISSUE TITLE
Add support for $prepopulate in the $apply operation

### ISSUE THREAD

**Issue by JPercival** [cqframework/clinical-reasoning#218]
As a user of $apply, I want support for the $prepopulate operation, so that I can run DTR workflows

Prerequisite: #214, #213 

We need to update the PlanDefinition runtime so that whenever an action of type prepopulate is encountered, the $prepopulate operation is run with the appropriate context. The action will define where to get the questionnaire from by URL (for the questionnaire) and by Endpoint (for the connection to the remote server). The referenced Questionnaire and supporting content should be loaded from the specified server. Then, the $prepopulate operation should be run. The returned questionnaire should have initial answers populated based on the CQL that's embedded in the Questionnaire (or in the linked Library) and the data that's available in the current data repository. The returned questionnaire should be embedded into the CarePlan/RequestGroup.

See the action extension that's in the eCR IG for an example of how to demark actions that represent calls to other operations: TODO: Bug JP for this.

Acceptance Criteria:
Test case for $apply using the example content from #214 exists and the test passes (meaning, the questionnaire is populated with initial answers).

**Comment by Capt-Mac** [comment]
pending #214
