### ISSUE TITLE
Create sample content representative of prior auth scenarios for definition-based extract

### ISSUE THREAD

**Issue by JPercival** [cqframework/clinical-reasoning#228]
As a developer, I need some sample content for definition-based extraction, so that I can ensure I do the implementation correctly.

This operation is primarily used for prior auth scenarios. The forms team also wants to know what the minimal set of types of responses are so that they can build a QA suite.

We need to find some representative or sample prior auth rules and work out what questionnaires we think would apply, and create examples for those.

Jason or Zach could be potential resources. Nikki could also provide a set of example rules.

Prerequisite for #227 

Acceptance Criteria:
Example Questionnaires and output FHIR Bundles are committed to the clinical-reasoning repository.

**Comment by JPercival** [comment]
NOTE: MVP needs to support the universal questionnaire, so that's top priority.

Nikki provided the sample questionnaire on 1/30/23

**Comment by barhodes** [comment]
A Questionnaire that has had the $prepopulate operation run against it:
https://github.com/cqframework/clinical-reasoning/blob/generate-questionnaire/evaluator.questionnaire/src/test/resources/org/opencds/cqf/cql/evaluator/questionnaire/r4/questionnaire-for-order-populated-errors.json

A Bundle response from an $apply call that calls $prepopulate:
https://github.com/cqframework/clinical-reasoning/blob/generate-questionnaire/evaluator.plandefinition/src/test/resources/org/opencds/cqf/cql/evaluator/plandefinition/r4/prepopulate/prepopulate-bundle.json

**Comment by JPercival** [comment]
Closed by #249
