### ISSUE TITLE
[Bug] Duplicate SDEs

### ISSUE THREAD

**Issue by JPercival** [cqframework/clinical-reasoning#239]
Issue: 
When aggregating multiple MeasureReports, we're getting duplicate SDE references and incorrect aggregation calculations.

Current test cases do not reproduce this error.

Steps to Reproduce:
1. run spark DQMP against cervical cancer screening, process over 1M patient bucket in s3
2. Output of report shows that SDE elements are aggregating values incorrectly. Many even come out as large negative integers like:  

```"code": "2106-3"
			}]
		},
		"valueInteger": -1692260774


"code": {
			"coding": [{
				"code": "F"
			}]
		},
		"valueInteger": -743565005
```

3. Output also shows several individual observations and references instead of aggregated counts

Expected result:

SDE aggregations that correctly sum references and omit unnecessary detail that can overwhelm large summary aggregations and performance

[EXM124 (4).txt](https://github.com/cqframework/clinical-reasoning/files/10665272/EXM124.4.txt)

**Comment by Capt-Mac** [comment]
Measure sources used: https://github.com/DBCG/connectathon/blob/master/fhir4/input/pagecontent/cql/EXM124_FHIR4-8.2.000.cql

**Comment by JPercival** [comment]
@Capt-Mac - May also be seeing this dQM Module

**Comment by Capt-Mac** [comment]
- SDE reference aggregation calculations
- SDE reference id’s are extraneous
- MeasureScore aggregation is incorrect

Example error report: https://outcomehealthcare.salessbx.smiledigitalhealth.com/fhir-request/MeasureReport/bc7abc5d-aaa8-4e22-adec-d759cdc89be3

Hapi branch being used: 
CDR branch being used: 

Scope:

Identify source of aggregation errors across MeasureReport resources

create an integration test that replicates the scenario and validates it is gone

**Comment by erbinnie** [comment]
Approved
