### ISSUE TITLE
Add translatorVersion to the set of translatorOptions that can potentially trigger a re-translate

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical-reasoning#250]
Currently, ELM translatorOptions are used to determine whether available ELM is appropriate for use, or whether it needs to be re-translated due to translatorOption expectations.

Consider whether we should add translatorVersion to the set of considerations for whether to re-translate.

This came up because there was a known issue with a previous translator version that resulted in incorrect ELM, and since the ELM was used directly in a measure package, rather than being re-translated with a newer version of the translator, it resulted in incorrect ELM being output with the measure package.

**Comment by mdnazmulkarim** [comment]
https://github.com/cqframework/clinical_quality_language/issues/843
