### ISSUE TITLE
Spike: Revisit Answer Attestation

### ISSUE THREAD

**Issue by JPercival** [cqframework/clinical-reasoning#269]
The DTR IG is currently being updated, and the way that attestation works is being revisited. We need to verify that our implementation is compliant with the latest IG that will be balloted in May.

DTR IG:
https://build.fhir.org/ig/HL7/davinci-dtr/specification.html

Acceptance Criteria:
* The IG is reviewed and any stories we need to work to be compliant are in the backlog.

**Comment by barhodes** [comment]
We will now return only the questionnaireresponse-author extension on items that are populated by CQL.  All other extensions are handled by the DTR app.
