### ISSUE TITLE
Replace animal-sniffer plugin with Javac "--release" flag

### ISSUE THREAD

**Issue by glemmon** [cqframework/clinical-reasoning#477]
Copied from the animal-sniffer Github page:

> Please note this plugin is now in maintenance level as the exact same feature can be now easily achieved using the --release flag from Javac see (https://openjdk.java.net/jeps/247)

**Comment by JPercival** [comment]
This project uses an extension for animal-sniffer to support Android. The Android SDK doesn't implement the full functionality of the the JDK at the same release level, so the plain ole `-release` flag isn't enough to ensure we have Android compatibility.

**Comment by JPercival** [comment]
See here for more information:
https://github.com/open-toast/gummy-bears?tab=readme-ov-file#android
