### ISSUE TITLE
Use coded improvement notation

### ISSUE THREAD

**Issue by brynrhodes** [cqframework/clinical-reasoning#80]
The logic currently looks for the word increase/decrease, rather than using the coded improvementNotation concepts (holdover from STU3 when it was only defined as text). Update this code to use the improvementNotation concepts

https://github.com/DBCG/cqf-ruler/blob/master/r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java#L302

**Comment by Capt-Mac** [comment]
uses code in clinical-reasoning code to set value
